[package]
name = "restkv"
version = "0.1.0"
authors = ["ahxxm <i@ahxxm.com>"]
edition = "2018"

[dependencies]
# web https://github.com/seanmonstar/warp
tokio = { version = "0.2", features = ["macros"] }
rand = "0.7.3" # random access-token
bytes = "0.5.6" # POST body
warp = "0.2.4" # routing
regex = "1.3.9" # validate param
lazy_static = "1.4.0" # global db instance

# file db, https://github.com/zshipko/rust-kv built on https://github.com/spacejam/sled
# NOTE: https://github.com/zshipko/rust-kv/blob/master/Cargo.toml#L17
# kv didn't enable compression in its toml, nor use semver...
kv = "0.20.2"
sled = { version = "0.31", features = ["compression"] }

# logger
log = { version = "0.4.11", features = ["max_level_debug", "release_max_level_info"] }
pretty_env_logger = "0.4.0"

[profile.release]
lto = true
