version: 2

jobs:
  build:
    docker:
      - image: ekidd/rust-musl-builder
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release --target x86_64-unknown-linux-musl
      - save_cache:
          paths:
            - /home/rust
            - /usr/local/cargo/registry
            - target/
          key: v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/restkv

