name: Build Package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - run: xz -kS "-${{ github.ref }}-x86_64.bin.xz" target/release/restkv
    - uses: ncipollo/release-action@v1
      with:
        artifact: target/debian/*.deb,target/release/*.bin.xz
        token: ${{ secrets.GITHUB_TOKEN }}
